spring.datasource.url=jdbc:postgresql://localhost:5433/bankdb
spring.datasource.username=bankuser
spring.datasource.password=bankpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
