spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username=bankuser
spring.datasource.password=bankpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true